<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_model extends CI_Model
{

    public $table = 'nilai_kategori';
    public $id = 'id_nilai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }


}

/* End of file Subkriteria_model.php */
/* Location: ./application/models/Subkriteria_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-29 15:35:40 */
/* http://harviacode.com */