<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');


function akses_url() {
echo base_url();
return;
}



/* End of file exportexcel_helper.php */
/* Location: ./application/helpers/exportexcel_helper.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-23 04:42:54 */
/* http://harviacode.com */